version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    env_file:
      - .env
    ports:
      - "5678:5678"
    depends_on:
      - postgres_ravenna
    networks:
      - ravenna_net
    restart: unless-stopped