version: "3.8"
services:
  chatwoot-postgres:
    image: postgres:15
    container_name: ravenna_chatwoot_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ravenna_chatwoot_db:/var/lib/postgresql/data

volumes:
  ravenna_chatwoot_db: